"""Type stubs for the _core C++ extension.

Hand-written rather than generated: the dimensional asymmetry of ``cross`` --
scalar for 2D, vector for 3D -- is expressed with ``@overload``, and no stub
generator infers that from the pybind11 signatures.
"""

from typing import final, overload

@final
class Point2:
    """A 2D point with double-precision coordinates. Immutable and hashable."""

    def __init__(self, x: float = ..., y: float = ...) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: Point2) -> Point2: ...
    def __sub__(self, other: Point2) -> Point2: ...
    def __mul__(self, scalar: float) -> Point2: ...
    def __rmul__(self, scalar: float) -> Point2: ...
    def __truediv__(self, scalar: float) -> Point2: ...
    def __neg__(self) -> Point2: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class Point3:
    """A 3D point with double-precision coordinates. Immutable and hashable."""

    def __init__(self, x: float = ..., y: float = ..., z: float = ...) -> None: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def z(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __add__(self, other: Point3) -> Point3: ...
    def __sub__(self, other: Point3) -> Point3: ...
    def __mul__(self, scalar: float) -> Point3: ...
    def __rmul__(self, scalar: float) -> Point3: ...
    def __truediv__(self, scalar: float) -> Point3: ...
    def __neg__(self) -> Point3: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@overload
def dot(a: Point2, b: Point2) -> float: ...
@overload
def dot(a: Point3, b: Point3) -> float: ...
@overload
def cross(a: Point2, b: Point2) -> float:
    """2D cross product: the scalar z-component of the 3D cross product."""

@overload
def cross(a: Point3, b: Point3) -> Point3:
    """3D cross product: a vector orthogonal to both operands."""
