#pragma once

// Deterministic generators for the adversarial coordinate families the
// predicates must survive: near-degenerate triples at magnitudes where naive
// double determinants have no significant digits left, exactly-representable
// circles, and UTM33-scale offsets.
//
// Every generator takes an explicit `std::mt19937_64`, so a test seeds once and
// the whole sequence is reproducible. No global RNG, no clock, no ambient state.

#include <terrain/core/point.hpp>
#include <terrain/predicates/orientation.hpp>

#include <array>
#include <cstdint>
#include <random>

namespace terrain::test {

// UTM33 easting/northing for mainland Norway, rounded to integers so the
// coordinates stay exactly representable and inside RefExact's range.
inline constexpr double utm33_easting = 500000.0;
inline constexpr double utm33_northing = 7900000.0;

[[nodiscard]] inline Point2 utm33_offset(const Point2& local) {
    return Point2{utm33_easting + local.x, utm33_northing + local.y};
}

// A triple whose exact orientation is known in closed form, positioned so that
// the naive determinant loses every significant digit.
//
// Construction: a is the origin, b = (bx, by), and c = k*b displaced by a tiny
// integer vector (e1, e2). Then
//
//     det(a, b, c) = bx*(k*by + e2) - by*(k*bx + e1) = bx*e2 - by*e1,
//
// so the answer is a product of small integers while the coordinates entering
// the determinant are around 2^50 and their products around 2^100. Every
// coordinate is an exactly representable integer, so nothing is lost before the
// predicate sees it; all the loss happens inside the predicate, which is the
// point.
struct KnownTriple {
    Point2 a;
    Point2 b;
    Point2 c;
    pred::Orientation expected;
};

[[nodiscard]] inline KnownTriple near_degenerate_triple(std::mt19937_64& rng) {
    std::uniform_int_distribution<std::int64_t> big{1 << 24, (1 << 25) - 1};
    std::uniform_int_distribution<std::int64_t> tiny{-2, 2};

    const std::int64_t bx = big(rng);
    const std::int64_t by = big(rng);
    const std::int64_t k = big(rng);

    std::int64_t e1 = 0;
    std::int64_t e2 = 0;
    std::int64_t det = 0;
    // Collinear triples are generated by the dedicated family below; here we
    // want a definite, tiny, nonzero answer.
    while (det == 0) {
        e1 = tiny(rng);
        e2 = tiny(rng);
        det = bx * e2 - by * e1;
    }

    const auto expected = det > 0 ? pred::Orientation::CounterClockwise : pred::Orientation::Clockwise;
    return KnownTriple{
        Point2{0.0, 0.0},
        Point2{static_cast<double>(bx), static_cast<double>(by)},
        Point2{static_cast<double>(k * bx + e1), static_cast<double>(k * by + e2)},
        expected,
    };
}

// The same construction with the displacement removed: exactly collinear at a
// magnitude where the naive determinant cannot confirm it.
[[nodiscard]] inline KnownTriple exactly_collinear_triple(std::mt19937_64& rng) {
    std::uniform_int_distribution<std::int64_t> big{1 << 24, (1 << 25) - 1};

    const std::int64_t bx = big(rng);
    const std::int64_t by = big(rng);
    const std::int64_t k = big(rng);

    return KnownTriple{
        Point2{0.0, 0.0},
        Point2{static_cast<double>(bx), static_cast<double>(by)},
        Point2{static_cast<double>(k * bx), static_cast<double>(k * by)},
        pred::Orientation::Collinear,
    };
}

// Integer points on the circle of radius 5 centred at the origin. Pythagorean,
// so the cocircularity is exact rather than approximate -- an implementation
// that returns Cocircular here is returning it for the right reason.
[[nodiscard]] inline std::array<Point2, 12> integer_circle_radius_5() {
    return {
        Point2{5, 0},   Point2{4, 3},   Point2{3, 4},   Point2{0, 5},
        Point2{-3, 4},  Point2{-4, 3},  Point2{-5, 0},  Point2{-4, -3},
        Point2{-3, -4}, Point2{0, -5},  Point2{3, -4},  Point2{4, -3},
    };
}

}  // namespace terrain::test
